services:
  app:
    build: .
    container_name: household-planner-web-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:18
    container_name: household-planner-db
    env_file:
      - .env
    volumes:
      - household_planner_db_data:/var/lib/postgresql    # <-- mount here instead
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  household_planner_db_data:
