CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "pwd" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "households" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_by" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "household_members" (
  "user_id" int NOT NULL,
  "household_id" int NOT NULL,
  "role" varchar,
  "joined_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "household_id")
);

CREATE TABLE "groceries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product" varchar NOT NULL,
  "brand" varchar,
  "amount" int,
  "unit" varchar,
  "store" varchar,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "picked" bool DEFAULT FALSE
);

CREATE TABLE "chores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "deadline" timestamp,
  "repeats" int,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "recipes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "img_url" varchar,
  "link" varchar,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

ALTER TABLE "household_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "household_members" ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "households" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "groceries" ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chores" ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipes" ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;
