CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "pwd" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "groceries_history" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INT NOT NULL,
  product VARCHAR NOT NULL,
  times_added INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE "households" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_by" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "version" INT NOT NULL DEFAULT 0
);

CREATE TABLE "household_members" (
  "user_id" int NOT NULL,
  "household_id" int NOT NULL,
  "role" varchar,
  "joined_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "household_id")
);

CREATE TABLE "groceries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product" varchar NOT NULL,
  "brand" varchar,
  "amount" varchar,
  "store" varchar,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "picked" bool DEFAULT false
);

CREATE TABLE "todos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "completed_at" timestamp
);

CREATE TABLE "recipes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "img_url" varchar,
  "link" varchar,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "restaurants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "household_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

ALTER TABLE "household_members"
ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "household_members"
ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "households"
ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "groceries"
ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "groceries_history"
ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "todos"
ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipes"
ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "restaurants"
ADD FOREIGN KEY ("household_id") REFERENCES "households" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "groceries_history"
ADD CONSTRAINT unique_household_product
UNIQUE (household_id, product);


-- Drop triggers if rerunning
DROP TRIGGER IF EXISTS groceries_bump ON groceries;
DROP TRIGGER IF EXISTS todos_bump ON todos;
DROP TRIGGER IF EXISTS members_bump ON household_members;
DROP TRIGGER IF EXISTS recipes_bump ON recipes;
DROP TRIGGER IF EXISTS restaurants_bump ON restaurants;

-- Function
CREATE OR REPLACE FUNCTION bump_household_version()
RETURNS TRIGGER AS $$
DECLARE
  hid INT;
BEGIN
  hid := COALESCE(NEW.household_id, OLD.household_id);

  UPDATE households
  SET version = version + 1,
      updated_at = now()
  WHERE id = hid;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers
CREATE TRIGGER groceries_bump
AFTER INSERT OR UPDATE OR DELETE
ON groceries
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER todos_bump
AFTER INSERT OR UPDATE OR DELETE
ON todos
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER members_bump
AFTER INSERT OR DELETE
ON household_members
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER recipes_bump
AFTER INSERT OR DELETE
ON recipes
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER restaurants_bump
AFTER INSERT OR DELETE
ON restaurants
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();
