CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    pwd TEXT NOT NULL,
    last_seen TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE households (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code VARCHAR(6) CHECK (char_length(code) = 6) NOT NULL UNIQUE,
    version INT NOT NULL DEFAULT 0,
    created_by INT NOT NULL REFERENCES users(id)
);

CREATE TYPE household_role AS ENUM ('owner', 'member');

CREATE TABLE household_members (
    user_id INT NOT NULL REFERENCES users(id),
    household_id INT NOT NULL REFERENCES households(id),
    role household_role NOT NULL DEFAULT 'member',
    PRIMARY KEY (user_id, household_id)
);

CREATE TABLE invites (
    token UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    household_id INT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    created_by INT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL,
    
    CONSTRAINT unique_product
    UNIQUE (name, brand)
);

CREATE TABLE grocery_lists (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    household_id INT NOT NULL REFERENCES households(id)
);

CREATE TABLE groceries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grocery_list_id INT NOT NULL REFERENCES grocery_lists(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(id),
    amount TEXT NOT NULL DEFAULT '',
    picked BOOL NOT NULL DEFAULT FALSE
);

CREATE TABLE groceries_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id INT NOT NULL REFERENCES households(id),
    product_id int NOT NULL REFERENCES products(id),
    times_added INT NOT NULL DEFAULT 1,
    CONSTRAINT unique_household_product_history UNIQUE (household_id, product_id)
);

CREATE TABLE recipes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    img_url TEXT,
    link TEXT,
    household_id INT NOT NULL REFERENCES households(id)
);

CREATE TABLE recipe_ingredient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(id),
    amount TEXT NOT NULL DEFAULT ''
);

CREATE TABLE todos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task TEXT NOT NULL,
    due TIMESTAMPTZ,
    repeat TEXT,
    frequency INT,
    next_id INT REFERENCES todos(id),
    household_id INT NOT NULL REFERENCES households(id),
    completed_at TIMESTAMPTZ
);

CREATE TABLE restaurants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cuisine TEXT NOT NULL,
    notes TEXT NOT NULL,
    household_id INT NOT NULL REFERENCES households(id)
);


-- Drop triggers if rerunning
DROP TRIGGER IF EXISTS groceries_bump ON groceries;
DROP TRIGGER IF EXISTS grocery_lists_bump ON grocery_lists;
DROP TRIGGER IF EXISTS todos_bump ON todos;
DROP TRIGGER IF EXISTS members_bump ON household_members;
DROP TRIGGER IF EXISTS recipes_bump ON recipes;
DROP TRIGGER IF EXISTS restaurants_bump ON restaurants;

-- Function
CREATE OR REPLACE FUNCTION bump_household_version()
RETURNS TRIGGER AS $$
DECLARE
    hid INT;
BEGIN
    hid := COALESCE(NEW.household_id, OLD.household_id);

    UPDATE households
    SET version = version + 1
    WHERE id = hid;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Groceries have no household_id of their own; derive it from the owning list.
CREATE OR REPLACE FUNCTION bump_household_version_from_list()
RETURNS TRIGGER AS $$
DECLARE
    hid INT;
    glid INT;
BEGIN
    glid := COALESCE(NEW.grocery_list_id, OLD.grocery_list_id);

    SELECT household_id INTO hid
    FROM grocery_lists
    WHERE id = glid;

    UPDATE households
    SET version = version + 1
    WHERE id = hid;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Triggers
CREATE TRIGGER groceries_bump
AFTER INSERT OR UPDATE OR DELETE
ON groceries
FOR EACH ROW
EXECUTE FUNCTION bump_household_version_from_list();

CREATE TRIGGER grocery_lists_bump
AFTER INSERT OR UPDATE OR DELETE
ON grocery_lists
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER todos_bump
AFTER INSERT OR UPDATE OR DELETE
ON todos
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER members_bump
AFTER INSERT OR DELETE
ON household_members
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER recipes_bump
AFTER INSERT OR DELETE
ON recipes
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();

CREATE TRIGGER restaurants_bump
AFTER INSERT OR DELETE
ON restaurants
FOR EACH ROW
EXECUTE FUNCTION bump_household_version();



-- ---------------------------------------
-- Setup defaults
--
-- ---------------------------------------

DO $$
DECLARE
steffo_id INT;
hid INT;
BEGIN

-- Users
INSERT INTO users (username, pwd)
VALUES ('steffe', '$2a$12$mQFPxKLUEGef.V8KQfYEau439Cg4no0XMl4fAzhrPpk2WQXOJj1r2')
ON CONFLICT (username) DO NOTHING;


SELECT id INTO steffo_id
FROM users
WHERE username = 'steffe';

-- Household
SELECT id INTO hid
FROM households
WHERE name = 'la casa' AND created_by = steffo_id
LIMIT 1;

IF hid IS NULL THEN
INSERT INTO households (name, code, created_by)
VALUES ('la casa', '234567', steffo_id)
RETURNING id INTO hid;
END IF;

-- Memberships
INSERT INTO household_members (user_id, household_id, role)
VALUES (steffo_id, hid, 'owner')
ON CONFLICT (user_id, household_id) DO NOTHING;


-- Grocery history
-- Your Go code adds each product 5 times.
-- Since your SQL schema stores a counter, seed each product once with times_added = 5.
INSERT INTO products (name, category)
VALUES
('Skinka', 'meat and fish'),
('Mjölk', 'dairy'),
('Lök', 'fruit & vegetables'),
('Tomat', 'fruit & vegetables'),
('Vispgrädde', 'dairy'),
('Bröd', 'pantry'),
('Persilja',  'fruit & vegetables'),
('Linguini', 'pantry'),
('Billys', 'other'),
('Oatly', 'pantry'),
('Bregott', 'dairy');

INSERT INTO groceries_history (
    household_id,
    product_id,
    times_added
)
VALUES
(1, 1, 5),
(1, 2, 5),
(1, 3, 5),
(1, 4, 5),
(1, 5, 5),
(1, 6, 5),
(1, 7, 5),
(1, 8, 5),
(1, 9, 5),
(1, 10, 5),
(1, 11, 5)
ON CONFLICT (household_id, product_id)
DO UPDATE SET
    times_added = EXCLUDED.times_added;
END;
$$;




