name: household-planner
services:
  db:
    image: postgres:18
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql    # <-- mount here instead
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db_data:
