services:
  db:
    image: postgres:18
    container_name: household-planner-db
    env_file:
      - .env
    volumes:
      - household_planner_db_data:/var/lib/postgresql    # <-- mount here instead
      - ./household-db/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  household_planner_db_data:
